### ISSUE TITLE
xunit generating invalid Junit xml

### ISSUE THREAD

**Issue by amerikan** [n1k0/casperjs#1458]
I'm using Jenkins CI and the xUnit plugin to run my casperjs tests. After upgrading to **phantomjs 2.1.1 / casperjs 1.1.0-beta5** I keep geting `[xUnit] [ERROR] - The result file '/var/lib/jenkins/workspace/PortalDev/log.xml' for the metric 'JUnit' is not valid. The result file has been skipped.` which is complaining about the xunit.

Environment: **Ubuntu 14.04.4 LTS** 

I downgraded back to **phantomjs 1.9.7 / casperjs 1.1.0-beta3** and the issue disappears. So something with either the latest casperjs or phantomjs is causing the problem. I'm not sure what is in charge of generating the xunit...

I've ran the casperjs self tests and they **pass** fine.

Here's the generated XML by both versions:

**phantomjs 2.1.1 / casperjs 1.1.0-beta5** :x: causes xUnit Error
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites xmlns="http://www.w3.org/1999/xhtml" time="11.977">
   <testsuite name="Sign In Page" tests="5" failures="0" errors="0" time="11.977" timestamp="2016-02-29T22:15:41.345Z" package="tests/suite/sign_in">
      <testcase name="Accept login with valid credentials" classname="tests/suite/sign_in" time="3.037" />
      <testcase name="Reject login with invalid credentials" classname="tests/suite/sign_in" time="3.544" />
      <testcase name="Sign Up page is reachable by top bar button" classname="tests/suite/sign_in" time="1.834" />
      <testcase name="Sign Up page is reachable by link at bottom of login forms" classname="tests/suite/sign_in" time="1.777" />
      <testcase name="Forgot Password page is reachable" classname="tests/suite/sign_in" time="1.785" />
      <system-out />
   </testsuite>
</testsuites>
```

**phantomjs 1.9.7 / casperjs 1.1.0-beta3** :white_check_mark: gives no problem!
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites time="16.811">
   <testsuite name="Sign In Page" tests="5" failures="0" errors="0" time="16.811" timestamp="2016-02-29T22:36:36.550Z" package="tests/suite/sign_in">
      <testcase name="Accept login with valid credentials" classname="tests/suite/sign_in" time="4.497" />
      <testcase name="Reject login with invalid credentials" classname="tests/suite/sign_in" time="4.349" />
      <testcase name="Sign Up page is reachable by top bar button" classname="tests/suite/sign_in" time="2.623" />
      <testcase name="Sign Up page is reachable by link at bottom of login forms" classname="tests/suite/sign_in" time="2.683" />
      <testcase name="Forgot Password page is reachable" classname="tests/suite/sign_in" time="2.659" />
      <system-out />
   </testsuite>
</testsuites>
```
The only difference I notice is the `xmlns="http://www.w3.org/1999/xhtml"` in line 2.

**Comment by amerikan** [comment]
@gboissinot do you happen to have an idea?

**Comment by mickaelandrieu** [comment]
As there is no update in xml generation between 1.0.3 and 1.0.5, it's probably an issue that comes from phantomJS.

"Patch" idea: check for xmlns attribute, if any, remove it.

**Comment by istr** [comment]
ping @amerikan any chance you can verify that it works again for you with current master? Thank you.

**Comment by amerikan** [comment]
@istr is there an easy to install from master using npm? I usually use npm to install casperjs.

**Comment by istr** [comment]
Something like this in your ```package.json``` for master / default branch

```json
  "dependencies": {
    "casperjs": "git+https://github.com/n1k0/casperjs.git"
  }
```

and for a branch named ```arbitrary-branch```

```json
  "dependencies": {
    "casperjs": "git+https://github.com/n1k0/casperjs.git#arbitrary-branch"
  }
```

**Comment by amerikan** [comment]
@istr I've updated to 1.1.0 and this is the error that is showing up now (different from the one I originally reported):

```shell
[xUnit] [ERROR] - Validation error on input
ERROR: Step ‘Publish xUnit test result report’ aborted due to exception: 
hudson.util.IOException2: There are some problems during the conversion into JUnit reports: 
	at org.jenkinsci.plugins.xunit.service.XUnitTransformer.invoke(XUnitTransformer.java:183)
	at org.jenkinsci.plugins.xunit.service.XUnitTransformer.invoke(XUnitTransformer.java:44)
	at hudson.FilePath.act(FilePath.java:990)
	at hudson.FilePath.act(FilePath.java:968)
	at org.jenkinsci.plugins.xunit.XUnitProcessor.performTests(XUnitProcessor.java:145)
	at org.jenkinsci.plugins.xunit.XUnitProcessor.performXUnit(XUnitProcessor.java:88)
	at org.jenkinsci.plugins.xunit.XUnitPublisher.perform(XUnitPublisher.java:142)
	at org.jenkinsci.plugins.xunit.XUnitPublisher.perform(XUnitPublisher.java:134)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:723)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:668)
	at hudson.model.Run.execute(Run.java:1763)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
Caused by: org.jenkinsci.plugins.xunit.exception.XUnitException: Validation error on input
	at org.jenkinsci.plugins.xunit.service.XUnitValidationService.validateInputFile(XUnitValidationService.java:77)
	at org.jenkinsci.plugins.xunit.service.XUnitTransformer.invoke(XUnitTransformer.java:132)
	... 16 more
Caused by: org.jenkinsci.lib.dtkit.util.validator.ValidationException: Validation error
	at org.jenkinsci.lib.dtkit.util.validator.ValidationService.processValidation(ValidationService.java:136)
	at org.jenkinsci.lib.dtkit.model.AbstractOutputMetric.validate(AbstractOutputMetric.java:62)
	at org.jenkinsci.plugins.xunit.types.JUnitInputMetric.validateInputFile(JUnitInputMetric.java:65)
	at org.jenkinsci.plugins.xunit.service.XUnitValidationService.validateInputFile(XUnitValidationService.java:66)
	... 17 more
Caused by: java.io.FileNotFoundException: /var/lib/jenkins/workspace/PortalDev/testsuites (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:623)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.startEntity(XMLEntityManager.java:1305)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.startDTDEntity(XMLEntityManager.java:1271)
	at com.sun.org.apache.xerces.internal.impl.XMLDTDScannerImpl.setInputSource(XMLDTDScannerImpl.java:263)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.dispatch(XMLDocumentScannerImpl.java:1167)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$DTDDriver.next(XMLDocumentScannerImpl.java:1050)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:964)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:118)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.jaxp.validation.StreamValidatorHelper.validate(StreamValidatorHelper.java:155)
	at com.sun.org.apache.xerces.internal.jaxp.validation.ValidatorImpl.validate(ValidatorImpl.java:116)
	at javax.xml.validation.Validator.validate(Validator.java:124)
	at org.jenkinsci.lib.dtkit.util.validator.ValidationService.processValidation(ValidationService.java:124)
	... 20 more
```

**Comment by BIGjuevos** [comment]
> Caused by: java.io.FileNotFoundException: /var/lib/jenkins/workspace/PortalDev/testsuites (No such file or directory)
Looks like it can't find the file.  Are you sure Jenkins is looking in the right spot?

**Comment by amerikan** [comment]
Yeah, I see that, but why does this error not show up in 1.1.0-beta4? I ran the test twice with 1.1.0 release and got the exceptions I pasted up above. I reverted back to 1.1.0-beta4 and the error disappears. Did some path change somewhere?

**Comment by istr** [comment]
@amerikan Ok, thanks for reporting that back. Could you re-check with **1.1-beta5**? That would help us to narrow down the git bisect needed to see what could be the root cause of the change. Thank you.

**Comment by amerikan** [comment]
Installed **1.1-beta5** and ran it, I get which is the original issue I reported:
```bash
[xUnit] [ERROR] - The result file '/var/lib/jenkins/workspace/PortalDev/log.xml' for the metric 'JUnit' is not valid. The result file has been skipped.
```

**Comment by istr** [comment]
@amerikan Ok, thank you. So it seems we have
- a regression 1.1-beta4 -> 1.1-beta5 (xml namespace)
- a regression 1.1-beta4 -> 1.1.0 (path)

We will try to bi-sect this. It could be helpful if you would elaborate a bit on the context, i.e. how does the java -> CasperJS call actually happen? (environment, code snippet, anything helps).

**Comment by amerikan** [comment]
Could it be a phantom 2.1.1 issue?

**Comment by istr** [comment]
> Could it be a phantom 2.1.1 issue?

Probably not, because CasperJS as of 1.1-beta4 does not install a specific PhantomJS version. It uses what you have installed in your environment.

**Comment by BIGjuevos** [comment]
@amerikan It is worth investigating if it is a phantomjs issue.

In the event it isn't I can test 1.1.0 with my Jenkins server at home.  What plugin/version are you using to show the test results?

**Comment by amerikan** [comment]
I tested different versions, here's a matrix of results:

  | phantom 1.9.8 | phantom 2.1.1
------------ | ------------- |  -------------
casper beta3 | :white_check_mark: | :heavy_multiplication_x: Incompatible version
casper beta4 | :white_check_mark: | :x: invalid junit
casper beta5 | :white_check_mark: | :x: invalid junit
casper 1.1.0 | :x: path exception | :x: path exception

**Comment by istr** [comment]
@amerikan Wow, thanks a lot. That helps to address this. I will dig into the path problem first.

**Comment by amerikan** [comment]
@istr glad that helps!

@BIGjuevos I'm using this plugin on jenkins https://wiki.jenkins-ci.org/display/JENKINS/xUnit+Plugin

**Comment by istr** [comment]
These two are susceptible to be the cause for the broken path:
https://github.com/n1k0/casperjs/issues/1479, https://github.com/n1k0/casperjs/pull/1483.

We still do not know, though, how you call CasperJS from Jenkins and what's your specific environment.

The difference in the search path for the output is obviously
```/var/lib/jenkins/workspace/PortalDev/testsuites``` (1.1.0)
vs
```/var/lib/jenkins/workspace/PortalDev/log.xml``` (up to beta5).

**Comment by amerikan** [comment]
@istr The original issue (xml problem) has been resolved. I'll close this and open a new one for the *new* problem, I'll reference this issue there.

**Comment by istr** [comment]
> The original issue (xml problem) has been resolved.

Really? According to your matrix it still fails for PhantomJS 2.1.1? Or am wrong?
As far as I can see we have two issues now:
- xunit output broken in PhantomJS 2.1.1
- path broken in CasperJS 1.1.0

**Comment by amerikan** [comment]
@istr casperjs 1.1.0 with either phantomjs 1.9.8 or 2.1.1 gives the path exception error.

**Comment by amerikan** [comment]
>We still do not know, though, how you call CasperJS from Jenkins and what's your specific environment.

Like this:
```bash
casperjs test tests/suite/ --includes=tests/routines.js --rooturl=http://example.org:80 --timeout=60 --ignore-ssl-errors=yes --xunit=log.xml
```

**Comment by BIGjuevos** [comment]
This issue was for the invalid XML which was solved?  Can we close this issue back out not that we have the other one open now?
